image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    # Markdown linting for docs and README
    - davidanson.vscode-markdownlint
    # Shell linting for the entrypoint script and scripts/*
    # among other shell files
    - timonwong.shellcheck
    # Fileicon theme Fireship.io uses in VS Code
    - vscode-icons-team.vscode-icons
    # Docker Stuff
    - ms-azuretools.vscode-docker
    # GitLens
    - eamodio.gitlens

tasks:
  # Initialize Keybase services first
  - before: |
      bash $GITPOD_REPO_ROOT/scripts/gp-ws-init
      gp sync-done run_keybase
  # Start our Compose instance in the background
  - name: Start Vault instance
    command: |
      gp sync-await run_keybase
      if [ ! -f docker-compose.yml ] && [ ! -f .env ]; then
        $GITPOD_REPO_ROOT/scripts/compose-init
      fi
      docker-compose up
